<?php

namespace App\Helpers;

class Status
{
    const USER_STATUS_OK = 'OK';
    const USER_STATUS_LOCK = 'LOCK';
    const PRODUCT_STATUS_AVAILABLE = 'AVAILABLE';
    const PRODUCT_STATUS_NEWS = 'NEWS';
    const PRODUCT_STATUS_PROMO = 'PROMOTION';
    const PRODUCT_STATUS_LACK = 'LACK';
    const CHECKOUT_STATUS_SUBMITTED = 'SUBMITTED';
    const CHECKOUT_STATUS_ACCEPTED = 'ACCEPTED';
    const CHECKOUT_STATUS_SENT = 'SENT';
    const CHECKOUT_STATUS_REALIZATION = 'REALIZATION';
    const REFERENCE_STATUS_NEW = 'NEW';
    const REFERENCE_STATUS_ACCEPT = 'ACCEPT';
    const REFERENCE_STATUS_MODIFY = 'MODIFY';
}
